name: Publish Retype powered website to GitHub Pages
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    name: Build with Retype
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Initialize submodules
        run: git submodule update --init --recursive
      - name: Install Retype
        run: npm install -g retypeapp@latest
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            7.0.x
            8.0.x
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}-v2
      - name: Build with Retype
        uses: retypeapp/action-build@latest
        env:
          RETYPE_LICENSE_KEY: ${{ secrets.RETYPE_LICENSE_KEY }}  # Add this line
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: retype-site
          path: .retype