name: Publish Retype powered website to GitHub Pages
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    name: Build with Retype
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Initialize and update submodules
        run: git submodule update --init --recursive
      - name: Setup .NET 7.0 and 8.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            7.0.x
            8.0.x
      - name: Build with Retype
        uses: retypeapp/action-build@latest
      - name: Upload Retype site
        uses: actions/upload-artifact@v3
        with:
          name: retype-site
          path: .retype

  deploy:
    name: Deploy to GitHub Pages
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download site artifact
        uses: actions/download-artifact@v3
        with:
          name: retype-site
          path: site
      - name: Deploy to retype branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          branch: retype
          force_orphan: true